# qa_guru_python_4_2

Test test_search_2 - заведомо с ошибкой, чтобы проверить отображение упавшего теста в результатах
